# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d9cd9f12d8b9805897efaf3f67c32418cc47710109a7ff7a070af5b5c247e3a1ca6a86c14aa60ec628ae804b72be9fc5d2326c2f221ea6ec2c55b3c0dfe16bf

test:
  secret_key_base: 3140c99539b3e7015d69e0bf05a5352da58fff432600328abe5e128738525181975fd68747c81b9e2e946884f558a81694afec7b303d2a86a1e8d46c4ae04201

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
